shop_app:
    resource: "@ShopBundle/Controller/AppController.php"
    type:     annotation

shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
