# app/config/security.yml

security:
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/new, roles: ROLE_ADMIN }
    - { path: ^/edit, roles: ROLE_ADMIN }

  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    UserBundle\Entity\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
# old stone authentification system 
#    in_memory:
#      memory:
#        users:
#          user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#          admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    main:
      entity:
        class:    UserBundle\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main_login:
        pattern:   ^/login$
        anonymous: true 
    main:
        pattern:   ^/
        anonymous: false
        provider:  main
        form_login:
          login_path: login
          check_path: login_check
        logout:
          path:       logout
          target:     /login


  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
