user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Security:login }

login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /login