<?php

namespace LocalRepoBundle\Repository;

/**
 * LocalAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalAppRepository extends \Doctrine\ORM\EntityRepository
{
}
